[server]
maxUploadSize = 200
maxMessageSize = 200

[theme]
base = "light"
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"

[browser]
gatherUsageStats = false